-- Add missing fields to npcs table
ALTER TABLE npcs ADD COLUMN IF NOT EXISTS alias VARCHAR(255);
ALTER TABLE npcs ADD COLUMN IF NOT EXISTS importance VARCHAR(100);
ALTER TABLE npcs ADD COLUMN IF NOT EXISTS role VARCHAR(255);
ALTER TABLE npcs ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE npcs ADD COLUMN IF NOT EXISTS timeline_tag VARCHAR(100);
ALTER TABLE npcs ADD COLUMN IF NOT EXISTS tags TEXT;
ALTER TABLE npcs ADD COLUMN IF NOT EXISTS armor_soak VARCHAR(100);
ALTER TABLE npcs ADD COLUMN IF NOT EXISTS defense_notes TEXT;
ALTER TABLE npcs ADD COLUMN IF NOT EXISTS ideals TEXT;
ALTER TABLE npcs ADD COLUMN IF NOT EXISTS bonds TEXT;
ALTER TABLE npcs ADD COLUMN IF NOT EXISTS flaws TEXT;
ALTER TABLE npcs ADD COLUMN IF NOT EXISTS goals TEXT;
ALTER TABLE npcs ADD COLUMN IF NOT EXISTS hooks TEXT;
ALTER TABLE npcs ADD COLUMN IF NOT EXISTS faction VARCHAR(255);
ALTER TABLE npcs ADD COLUMN IF NOT EXISTS relationships TEXT;
ALTER TABLE npcs ADD COLUMN IF NOT EXISTS attitude_toward_party VARCHAR(100);
ALTER TABLE npcs ADD COLUMN IF NOT EXISTS resources TEXT;
