-- Full audit migration to sync online database with db_schema.sql
-- Generated: 2025-11-27
-- This will add all missing columns to campaign_characters table

-- Add all missing columns to campaign_characters
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS player_name varchar(255);
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS campaign_name varchar(255);
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS race_id varchar(36) REFERENCES races(id) ON DELETE SET NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS race varchar(255);
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS age integer;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS base_magic integer;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS base_movement integer;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS sex varchar(50);
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS height integer;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS weight integer;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS skin_color varchar(100);
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS eye_color varchar(100);
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS hair_color varchar(100);
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS deity varchar(255);
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS defining_marks text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS fame integer DEFAULT 0 NOT NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS experience integer DEFAULT 0 NOT NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS total_experience integer DEFAULT 0 NOT NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS quintessence integer DEFAULT 0 NOT NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS total_quintessence integer DEFAULT 0 NOT NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS strength integer DEFAULT 25 NOT NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS dexterity integer DEFAULT 25 NOT NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS constitution integer DEFAULT 25 NOT NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS intelligence integer DEFAULT 25 NOT NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS wisdom integer DEFAULT 25 NOT NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS charisma integer DEFAULT 25 NOT NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS skill_allocations jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS personality text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS ideals text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS bonds text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS flaws text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS goals text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS secrets text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS backstory text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS motivations text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS hooks text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS faction text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS relationships text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS attitude_toward_party text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS allies text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS enemies text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS affiliations text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS resources text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS credits_remaining integer DEFAULT 0 NOT NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS equipment jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS hp_total integer;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS initiative integer;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS mana integer;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS armor_soak varchar(100);
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS defense_notes text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS challenge_rating integer;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS skill_checkpoint jsonb;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS is_initial_setup_locked boolean DEFAULT false NOT NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS xp_spent integer DEFAULT 0 NOT NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS xp_checkpoint integer DEFAULT 0 NOT NULL;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE campaign_characters ADD COLUMN IF NOT EXISTS is_setup_complete boolean DEFAULT false NOT NULL;
